import os
import time
import getpass
def rhel_initial():
    os.system("clear")
    print("\n \t\t\tWelcome to the Red Hat Linux Management Console\n")
    print("\n\t\t **---> Press <---**\n")
    time.sleep(1)
    print("\n\t  1 -> To see date & calender ")
    time.sleep(1)
    print("\n\t  2 -> To create directory ")
    time.sleep(1)
    print("\n\t  3 -> To see your memory details ")
    time.sleep(1)
    print("\n\t  4 -> To see your Hard Disk details")
    time.sleep(1)
    print("\n\t  5 -> To setup webserver ")
    time.sleep(1)
    print("\n\t  6 -> To check connection ")
    time.sleep(1)
    print("\n\t  7 -> To change to root user ")
    time.sleep(1)
    print("\n\t  8 -> To install any software ")
    time.sleep(1)
    print("\n\t  9 -> To start any service or daemon  ")
    time.sleep(1)
    print("\n\t  10 -> To Reboot your machine")
    time.sleep(1)
    print("\n\t  11 -> To shut down your machine ")
    time.sleep(1)
    print("\n\t  12 -> To exit from this console/ Get back to main dashboard ")
    time.sleep(1)
    return
rhel_initial()
while True :
#    rhel_initial()
    print("\n\t\t  Enter your choice :", end="")
    ch = int(input())
    if ch == 1:
        print("\n \t\t Press enter to continue ..\n.")   
        input()
        os.system("\n\t\t date")
        time.sleep(1)
        os.system("\n\t\t cal")
        print("\n \t\t Press enter to continue ..\n.")   
        input()
        rhel_initial()
    elif ch == 2:
        print("\n\t\t\t Enter the name of the directory with full path..\n ", end="")
        dir = input()
        print("\n \t\t Press enter to continue ..\n.")
        input()
        os.system("mkdir {o}".format(dir))
        time.sleep(1)
        print("\n\t Successfully created..")
        print("\n \t\t Press enter to continue ..\n.")
        input()
        rhel_initial()
    elif ch == 3:
        time.sleep(1)
        print("\n\t\t\t Your Memory details is shown below :\n")
        os.system("free -m")
        print("\n \t\t Press enter to continue ..\n.")
        input()
        rhel_initial()
    elif ch == 4:
        time.sleep(1)
        print("\n\t\t\t Your HD details is shown below :\n")
        os.system("df -h")
        print("\n \t\t Press enter to continue ..\n.")
        input()
        rhel_initial()
    elif ch == 5:
        print("\n\t\t Press enter after entering the code of Web Page ..")
        time.sleep(1)
        os.system("yum install httpd -y")
        os.system("cat > /var/www/html/index.html")
        os.system("setenforce 0")
        os.system("systemctl start httpd")
        print("ALL DONE")
        print("\n \t\t Press enter to continue ..\n.")
        input()
        rhel_initial()
    elif ch == 6:
        time.sleep(1)
        print("\n\t\t Pinging to 8.8.8.8..\n")
        os.system("ping -c 4  8.8.8.8")
        print("\n \t\t Press enter to continue ..\n.")
        input()
        rhel_initial()
    elif ch == 7:
        time.sleep(1)
        print("\n\t\t Enter your Root password..(if asks)\n")
        os.system("sudo su - root")
        print("\n \t\t Press enter to continue ..\n.")
        input()
        rhel_initial()
    elif ch == 8:
        time.sleep(1)
        print("\n\t\t Please enter the name of software you want :")
        time.sleep(1)
        os.system("yum install {0} -y".format(sw))
        print("\n \t\t Press enter to continue ..\n.")
        input()
        rhel_initial()
    elif ch == 9:
        time.sleep(1)
        print("\n\t\t\ Please enter the name of service you want to start :")
        os.system("systemctl  start  {0}".format(daemon))
        print("\n \t\t Press enter to continue ..\n.")
        input()
        rhel_initial()
    elif ch == 10:
        time.sleep(1)
        print("\n\t\t Rebooting your system...\n")
        time.sleep(1)
        print("\n \t\t Press enter to continue ..\n.")
        input()
        os.system("init 6")
    elif ch == 11:
        time.sleep(1)
        print("\n\t\t Shutting down your RHEL 8..\n")
        time.sleep(1)
        print("\n \t\t Press enter to continue ..\n.")
        input()
        os.system("init 0")
    elif ch == 12:
        time.sleep(1)
        print("\n\t\t Byee BYee... Going to the main dashboard")
        time.sleep(2)
        exit()
    else:
        time.sleep(1)
        print("\n\n\t\t Invalid Choice... Try Again\n")
        time.sleep(1)
        rhel_initial()
